# Generated by Django 3.2.9 on 2021-11-20 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='totol_price',
            new_name='total_price',
        ),
    ]
